### ISSUE TITLE
Can't load save with 2024.3.0

### ISSUE THREAD

**Issue by fauxnik** [t0stiman/rr_better_mouse_mod#14]
I get an error when I attempt to load an existing save with this mod installed and the latest version of the game. The save loads successfully when I uninstall this mod. Attached is the player log from such an attempt.

[Player.log](https://github.com/t0stiman/rr_better_mouse_mod/files/14736215/Player.log)

**Comment by t0stiman** [comment]
Does the error still occur with this version of the mod?

[better_mouse_mod.zip](https://github.com/t0stiman/rr_better_mouse_mod/files/14754599/better_mouse_mod.zip)

**Comment by t0stiman** [comment]
Good
