### ISSUE TITLE
UMM Installer not detecting updates

### ISSUE THREAD

**Issue by AMacro** [t0stiman/rr_better_mouse_mod#4]
Multiple versions in Repository.json is confusing UMM Installer

UMM Installer appears to be taking the first entry where the ID matches, rather than looking for the highest version for the ID, consequently, the UMM installer app does not show an update available.

UMM In-Game component appears to get the latest version correctly.

Might be worth putting just the latest version into the repository.json

**Comment by t0stiman** [comment]
I looked at some other UMM mods and they all have the newest version at the top. I'll try that.  
Thanks for the report

**Comment by t0stiman** [comment]
I tested and it works now. Let me know if it doesn't work for you
