### ISSUE TITLE
Disabling toggle camera movement doesn't work

### ISSUE THREAD

**Issue by mricher-git** [t0stiman/rr_better_mouse_mod#5]
If you uncheck the "Toggle camera movement" it behaves like the toggle is stuck on, it doesn't wait for right mouse to be pressed.

I really like the removal of camera smoothness though, could you fix the toggle and make camera smoothing a seperate option?

**Comment by t0stiman** [comment]
and by now I mean soon™

**Comment by mricher-git** [comment]
Seems to be working now, except pressing escape still closes windows

**Comment by t0stiman** [comment]
You need to restart the game to apply that one. And make sure you enabled it in the mod settings menu
