### ISSUE TITLE
[Feature Request] Pause button rebinding

### ISSUE THREAD

**Issue by fauxnik** [t0stiman/rr_better_mouse_mod#6]
Some folks may not have pause buttons on their keyboard. Allowing the pause button to be rebound would make this useful feature useful to all.

**Comment by fauxnik** [comment]
"Asking for a friend." 😉

**Comment by t0stiman** [comment]
Hi Niko!
Do you have one of those keyboards that miss a lot of keys?

**Comment by fauxnik** [comment]
Yes, no numpad, prntscr, pause, etc.

**Comment by t0stiman** [comment]
TBH I'm probably not going to implement this. Maybe you could make it and send me a PR?
