### ISSUE TITLE
First Person leaning

### ISSUE THREAD

**Issue by Hank-Kerchief** [t0stiman/rr_better_mouse_mod#7]
When in first-person mode, the camera seems to be off-center, as leaning (Q or E) moves the camera in a random direction.  A likely related issue is climbing the ladder onto the locomotive, when you get to the top, you fall off the ladder either to the left or right instead of going forward into the locomotive.  Again, likely because the camera seems to be off-center.

**Comment by t0stiman** [comment]
Hi Hank (clever username BTW),

I noticed this bug already and I've been investigating it. I don't quite understand what's happening yet but I think it has something to do with the rotation of the player's avatar vs the rotation of the camera.

**Comment by t0stiman** [comment]
fixed it!

**Comment by t0stiman** [comment]
Fixing this broke some other stuff... I need to really redesign the camera systems...

**Comment by Hank-Kerchief** [comment]
> Fixing this broke some other stuff... I need to really redesign the camera systems...

Does that mean you have reverted the version?  I have no clue how you are able to figure this modding stuff out, so I appreciate what you are able to do.  Thanks for adding to the game.

**Comment by t0stiman** [comment]
Fixed in the new mod update
